apiVersion: v1
kind: Namespace
metadata:
  name: security-lab
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-update-mode: "Off"
    optimization.security-lab/mode: recommendation-only
