apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-radar-continuous-scan
  namespace: security-lab
  labels:
    app.kubernetes.io/name: vault-radar-continuous-scan
  annotations:
    eks.amazonaws.com/role-arn: VAULT_RADAR_IRSA_ROLE_ARN_PLACEHOLDER
automountServiceAccountToken: true
