from __future__ import annotations

from typing import Any

from app import automation
from app.automation import AutomationService


class _Result:
    def __init__(
        self,
        rows: list[dict[str, Any]] | None = None,
        *,
        rowcount: int = 0,
    ):
        self._rows = rows or []
        self.rowcount = rowcount

    def fetchall(self) -> list[dict[str, Any]]:
        return list(self._rows)

    def fetchone(self) -> dict[str, Any] | None:
        return self._rows[0] if self._rows else None


class _RecordingPostgresConnection:
    postgres = True

    def __init__(self):
        self.statements: list[tuple[str, Any]] = []
        self.scripts: list[str] = []
        self.closed = False

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.closed = True
        return False

    def execute(self, statement: str, parameters: Any = None) -> _Result:
        self.statements.append((statement, parameters))
        normalized = " ".join(statement.split())
        if "FROM information_schema.columns" in normalized:
            return _Result([{"name": "id"}])
        if "FROM automation_audit ORDER BY id ASC" in normalized:
            return _Result()
        return _Result()

    def executescript(self, script: str) -> None:
        self.scripts.append(script)


def test_postgres_automation_schema_uses_shared_adapter_and_native_guards(
    monkeypatch,
):
    connection = _RecordingPostgresConnection()
    monkeypatch.setattr(
        automation,
        "connect_database",
        lambda target: connection,
    )

    service = AutomationService(
        "postgresql://portal@database.internal/security_portal"
    )

    executed = "\n".join(
        [*connection.scripts, *(statement for statement, _ in connection.statements)]
    )
    assert service.path.startswith("postgresql://")
    assert connection.closed is True
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in executed
    assert "FROM information_schema.columns" in executed
    assert "ADD COLUMN IF NOT EXISTS previous_hash" in executed
    assert "security_portal_reject_automation_audit_mutation" in executed
    assert "BEFORE UPDATE ON automation_audit" in executed
    assert "BEFORE DELETE ON automation_audit" in executed
    assert "PRAGMA" not in executed
    assert "AUTOINCREMENT" not in executed
    assert "SELECT RAISE" not in executed


def test_postgres_automation_writes_lock_rows_and_dispatch_scope(monkeypatch):
    connection = _RecordingPostgresConnection()
    monkeypatch.setattr(
        automation,
        "connect_database",
        lambda target: connection,
    )
    service = AutomationService(
        "postgresql://portal@database.internal/security_portal"
    )
    connection.statements.clear()

    service._begin_write(connection)
    service._request_row(connection, "automation-test", for_update=True)
    service._lock_dispatch_scope(connection, "cert_renew", "certificate:portal")

    statements = [
        (" ".join(statement.split()), parameters)
        for statement, parameters in connection.statements
    ]
    assert statements[0] == ("BEGIN", None)
    assert statements[1][0].endswith("WHERE id = ? FOR UPDATE")
    assert statements[1][1] == ("automation-test",)
    assert statements[2][0] == "SELECT pg_advisory_xact_lock(?)"
    assert isinstance(statements[2][1][0], int)


def test_postgres_automation_list_omits_untyped_null_filter(monkeypatch):
    connection = _RecordingPostgresConnection()
    monkeypatch.setattr(
        automation,
        "connect_database",
        lambda target: connection,
    )
    service = AutomationService(
        "postgresql://portal@database.internal/security_portal"
    )
    connection.statements.clear()

    assert service.list(limit=25, offset=5) == []

    statement, parameters = connection.statements[-1]
    assert "IS NULL" not in statement
    assert parameters == (25, 5)
