apiVersion: v1
kind: ConfigMap
metadata:
  name: security-platform-prometheus-scrape-config
  namespace: security-lab
  labels:
    app.kubernetes.io/name: security-platform-observability
    app.kubernetes.io/part-of: information-security-portal
data:
  additional-scrape-configs.yaml: |
    - job_name: vault
      metrics_path: /v1/sys/metrics
      params:
        format:
          - prometheus
      static_configs:
        - targets:
            - vault.service.consul:8200
          labels:
            product: vault
            environment: lab

    - job_name: terraform-enterprise
      metrics_path: /metrics
      static_configs:
        - targets:
            - tfe.internal.example:9090
          labels:
            product: terraform-enterprise
            environment: lab

    - job_name: keycloak
      metrics_path: /metrics
      static_configs:
        - targets:
            - keycloak.security-lab.svc.cluster.local:8080
          labels:
            product: keycloak
            environment: lab

    - job_name: security-portal
      metrics_path: /metrics
      static_configs:
        - targets:
            - security-portal.security-lab.svc.cluster.local:8080
          labels:
            product: security-portal
            environment: lab

    - job_name: rds-postgresql
      metrics_path: /metrics
      static_configs:
        - targets:
            - postgres-exporter.security-lab.svc.cluster.local:9187
          labels:
            product: rds-postgresql
            environment: lab

    - job_name: elastic
      metrics_path: /metrics
      static_configs:
        - targets:
            - elasticsearch-exporter.security-lab.svc.cluster.local:9114
          labels:
            product: elastic
            environment: lab
